const baseUrl = '/api'

export default{
    postlogin: baseUrl + '/users/postlogin',
    register:baseUrl + '/users/registerinfo',
    logout: baseUrl + '/users/logout',
    userinfo: baseUrl + '/users/userinfo',
    getwebinfo:baseUrl+'/users/getwebinfo',
    edituserinfo:baseUrl+'/users/edituserinfo',
    uploadimg:baseUrl+'/users/uploadimg',
    updateAvatar:baseUrl+'/users/updateAvatar',
    updatepassword:baseUrl+'/users/updatepassword',
    share:baseUrl+'/users/share',
    getmyshare:baseUrl+'/users/getmyshare',
    getshareinfos:baseUrl+'/users/getshareinfos',
    getsharedetail:baseUrl+'/users/getsharedetail',
    getuserinfo:baseUrl+'/users/getuserinfo',
    comment:baseUrl+'/users/comment',
    getcomments:baseUrl+'/users/getcomments',
    like:baseUrl+'/users/like',
    unlike:baseUrl+'/users/unlike',
    isliked:baseUrl+'/users/isliked',
    delcomment:baseUrl+'/users/delcomment',
    searchtest:baseUrl+'/users/searchtest',
    searcharticles:baseUrl+'/users/searcharticles',
    getreward:baseUrl+'/users/getreward',
    getmylikes:baseUrl+'/users/getmylikes',
    delarticle:baseUrl+'/users/delarticle',
    comothers:baseUrl+'/users/comothers',
    getresponse:baseUrl+'/users/getresponse',
    findpassword:baseUrl+'/users/findpassword',
    follow:baseUrl+'/users/follow',
    unfollow:baseUrl+'/users/unfollow',
    isfollow:baseUrl+'/users/isfollow',
    editshare:baseUrl+'/users/editshare',
    getmyfollow:baseUrl+'/users/getmyfollow',
    getmycomments:baseUrl+'/users/getmycomments',
    delresponse:baseUrl+'/users/delresponse',
}